### PR TITLE
refactor: making types more consistant + more test + ...

### LINKED ISSUE #9: escaped spaces are weird
requires one character too much
I'll try to fix that in #8 (`discard` needs to be handled)

### PR DESCRIPTION
**Pull request by Conni2461**
Fix #9

FYI this project is not abandoned (yet). I am not prime, i maintain projects for at least a week. :rofl: 
I also have another performance improvement idea. Need to verify.
PR is still WIP. I need to convert more types

After this PR:
- Fix prefix highlighting
- Unicode
  - normalize
  - case
- Abandon project ;)

### CODE REVIEW

**Comment by Conni2461** [comment]
Note, do i want to move the discard handling to c?! So all that i needs to happen in lua land is `if pattern_obj.discard then clear table end`

**Comment by Conni2461** [comment]
This branch might be faster than main:

image

**Comment by tami5** [comment]
Just test it out, no issues and feels a bit faster indeed :star_struck:. On master, when launching the picker it, fzf used to take few milliseconds to start up and for the sections to appear

**Comment by Conni2461** [comment]
Lets get this to main. (what could go wrong :laughing:)

I am already working on utf8 support ;)

**Pull request merged**
