### PR TITLE
Detect MSYS

### LINKED ISSUE #88: PR #87 breaks the use of MinGW make on Windows
https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/87

Output follows. Note that I have to type `exit` to exit the interactive shell.

```
C:\Users\bakkenl\AppData\Local\nvim\pack\nvim-telescope\start\telescope-fzf-native.nvim>make --version
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

C:\Users\bakkenl\AppData\Local\nvim\pack\nvim-telescope\start\telescope-fzf-native.nvim>git clean -xffd

C:\Users\bakkenl\AppData\Local\nvim\pack\nvim-telescope\start\telescope-fzf-native.nvim>make
cmd //C mkdir build
Microsoft Windows [Version 10.0.22000.1219]
(c) Microsoft Corporation. All rights reserved.

C:\Users\bakkenl\AppData\Local\nvim\pack\nvim-telescope\start\telescope-fzf-native.nvim>exit
gcc -O3 -Wall -Werror -fpic -std=gnu99 -shared src/fzf.c -o build/libfzf.dll
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file build/libfzf.dll: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:18: build/libfzf.dll] Error 1
```

The fix is to revert the extra escaping introduced in #87, or to improve system detection.

I'll open a PR to address this.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #88

### CODE REVIEW

**Comment by Conni2461** [comment]
Thanks :)

i am sorry that i merge so late, i wanted someone to confirm if this fixes #82  + #88 + #90 (see #90 for conversation).

I sadly cant do any testing of my own

**Comment by lukebakken** [comment]
I will open a PR to add a Windows CI pipeline, which should catch regressions like #88

**Comment by Conni2461** [comment]
We actually had a windows pipeline which build the makefile but we replaced it with cmake because it seemed to work better on windows and is now the preferred way to build on windows (even though i hate cmake).

The problem with windows is that there are so many different environments to build the binary. Mingw, MSVC (normal terminal, powershell) and there definitly was an issue that was adressed with #88.

So yeah i dont know how to fix that. Like the plugin was done after a week and i only had to refine a couple of time and add smaller features but the build system was rewitten 100 times and all we do is compile 1 c file  :(

**Comment by lukebakken** [comment]
I have no idea why I didn't think there is a Windows CI pipeline currently, but there it is. I must have been looking at something old. `cmake` works great on my machine, so thanks for pointing that out.

IMHO it would be reasonable for you to say "if you're on Windows, use `cmake`" and leave it as the only supported option.

**Pull request merged**
